DELETE FROM FILM_LIKES;
DELETE FROM FRIENDSHIP;
DELETE FROM FILMS_GENRES;
DELETE FROM FILM;
DELETE FROM FRIENDSHIP_STATUS;
DELETE FROM USERS;
DELETE FROM GENRE;
DELETE FROM RATING_MPA;

-- RATING_MPA с явными ID
INSERT INTO RATING_MPA (RATING_ID, NAME) VALUES
  (1, 'G'),
  (2, 'PG'),
  (3, 'PG-13'),
  (4, 'R'),
  (5, 'NC-17');

-- GENRE
INSERT INTO GENRE (GENRE_ID, NAME) VALUES
  (1, 'Комедия'),
  (2, 'Драма'),
  (3, 'Мультфильм'),
  (4, 'Триллер'),
  (5, 'Документальный'),
  (6, 'Боевик');


-- FRIENDSHIP_STATUS
INSERT INTO FRIENDSHIP_STATUS (FRIENDSHIP_STATUS_ID, NAME, IS_ACCEPTED) VALUES
  (1, 'Заявка отправлена', FALSE),
  (2, 'Подтверждена', TRUE),
  (3, 'Отклонена', FALSE);
