--ALTER TABLE RATING_MPA ALTER COLUMN RATING_ID RESTART WITH 1;
--ALTER TABLE GENRE ALTER COLUMN GENRE_ID RESTART WITH 1;
--ALTER TABLE USERS ALTER COLUMN USER_ID RESTART WITH 1;
--ALTER TABLE FILM ALTER COLUMN FILM_ID RESTART WITH 1;
--ALTER TABLE FRIENDSHIP ALTER COLUMN FRIENDSHIP_ID RESTART WITH 1;
--ALTER TABLE FRIENDSHIP_STATUS ALTER COLUMN FRIENDSHIP_STATUS_ID RESTART WITH 1;
---------------------------------------
-- TABLE RATING_MPA
---------------------------------------
CREATE TABLE IF NOT EXISTS PUBLIC.RATING_MPA (
    RATING_ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR_IGNORECASE(255) NOT NULL,
    CONSTRAINT RATING_MPA_PK PRIMARY KEY (RATING_ID)
);

---------------------------------------
-- TABLE GENRE
---------------------------------------
CREATE TABLE IF NOT EXISTS PUBLIC.GENRE (
    GENRE_ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR_IGNORECASE(255) NOT NULL,
    CONSTRAINT GENRE_PK PRIMARY KEY (GENRE_ID)
);

---------------------------------------
-- TABLE USERS   ← исправлено
---------------------------------------
CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
    USER_ID INTEGER NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR_IGNORECASE(255) NOT NULL,
    LOGIN VARCHAR_IGNORECASE(255) NOT NULL,
    NAME VARCHAR_IGNORECASE(255),
    BIRTHDAY DATE NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);

---------------------------------------
-- TABLE FILM
---------------------------------------
CREATE TABLE IF NOT EXISTS PUBLIC.FILM (
    FILM_ID INTEGER NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR_IGNORECASE(1000) NOT NULL,
    NAME VARCHAR_IGNORECASE(255) NOT NULL,
    RELEAS_DATE DATE NOT NULL,
    DURATION INTEGER NOT NULL,
    RATING_MPA_ID INTEGER,
    CONSTRAINT FILM_PK PRIMARY KEY (FILM_ID),
    CONSTRAINT FILM_RATING_MPA_FK FOREIGN KEY (RATING_MPA_ID)
        REFERENCES PUBLIC.RATING_MPA(RATING_ID)
        ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS FILM_RATING_MPA_FK_INDEX ON PUBLIC.FILM (RATING_MPA_ID);

---------------------------------------
-- TABLE FILMS_GENRES
---------------------------------------
CREATE TABLE IF NOT EXISTS PUBLIC.FILMS_GENRES (
    GENRE_ID INTEGER NOT NULL,
    FILM_ID INTEGER NOT NULL,
    CONSTRAINT FILMS_GENRES_FILM_FK FOREIGN KEY (FILM_ID)
        REFERENCES PUBLIC.FILM(FILM_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FILMS_GENRES_GENRE_FK FOREIGN KEY (GENRE_ID)
        REFERENCES PUBLIC.GENRE(GENRE_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE INDEX IF NOT EXISTS FILMS_GENRES_FILM_FK_INDEX ON PUBLIC.FILMS_GENRES (FILM_ID);
CREATE INDEX IF NOT EXISTS FILMS_GENRES_GENRE_FK_INDEX ON PUBLIC.FILMS_GENRES (GENRE_ID);

---------------------------------------
-- TABLE FILM_LIKES
---------------------------------------
CREATE TABLE IF NOT EXISTS PUBLIC.FILM_LIKES (
    FILM_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CONSTRAINT FILM_LIKES_FILM_FK FOREIGN KEY (FILM_ID)
        REFERENCES PUBLIC.FILM(FILM_ID)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FILM_LIKES_USER_FK FOREIGN KEY (USER_ID)
        REFERENCES PUBLIC.USERS(USER_ID)   -- исправлено
        ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS FILM_LIKES_FILM_FK_INDEX ON PUBLIC.FILM_LIKES (FILM_ID);
CREATE INDEX IF NOT EXISTS FILM_LIKES_USER_FK_INDEX ON PUBLIC.FILM_LIKES (USER_ID);

---------------------------------------
-- TABLE FRIENDSHIP_STATUS
---------------------------------------
CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDSHIP_STATUS (
    FRIENDSHIP_STATUS_ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR_IGNORECASE(255) NOT NULL,
    IS_ACCEPTED BOOLEAN NOT NULL,
    CONSTRAINT FRIENDSHIP_STATUS_PK PRIMARY KEY (FRIENDSHIP_STATUS_ID)
);

---------------------------------------
-- TABLE FRIENDSHIP
---------------------------------------
CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDSHIP (
    USER_ID INTEGER NOT NULL,
    FRIEND_ID INTEGER NOT NULL,
    FRIENDSHIP_STATUS_ID INTEGER NOT NULL,

    -- составной первичный ключ из внешних ключей
    CONSTRAINT FRIENDSHIP_PK PRIMARY KEY (USER_ID, FRIEND_ID),

    -- внешние ключи
    CONSTRAINT FRIENDSHIP_USER_FK FOREIGN KEY (USER_ID)
        REFERENCES PUBLIC.USERS(USER_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT FRIENDSHIP_FRIEND_FK FOREIGN KEY (FRIEND_ID)
        REFERENCES PUBLIC.USERS(USER_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT FRIENDSHIP_STATUS_FK FOREIGN KEY (FRIENDSHIP_STATUS_ID)
        REFERENCES PUBLIC.FRIENDSHIP_STATUS(FRIENDSHIP_STATUS_ID)
        ON DELETE SET NULL ON UPDATE CASCADE
);

-- индексы для ускорения поиска по внешним ключам
CREATE INDEX IF NOT EXISTS FRIENDSHIP_STATUS_FK_INDEX
    ON PUBLIC.FRIENDSHIP (FRIENDSHIP_STATUS_ID);

CREATE INDEX IF NOT EXISTS FRIENDSHIP_USER_FK_INDEX
    ON PUBLIC.FRIENDSHIP (USER_ID);

CREATE INDEX IF NOT EXISTS FRIENDSHIP_FRIEND_ID_FK_INDEX
    ON PUBLIC.FRIENDSHIP (FRIEND_ID);
